### PR TITLE
fix: Absence of global Prisma namespace for a new client

### LINKED ISSUE #516: Invalid Typescript types using prisma-client generator on v6.11.1
### Prerequisites

- [x] I have written a clear issue title
- [x] I have searched existing issues to avoid duplicates

### Versions

Prisma 6.11.1
prisma-json-types-generator 3.5.1

### A minimal reproducible example

https://github.com/arthurfiorette/prisma-json-types-generator

### Bug Description

Hi, I've just upgraded our project to v.6.11.1 and decided to switch to multi-file schema + new `prisma-cleint` generator (due type splitting function).

Appears everything works fine with latest json-generator, but checking manually types generated by prisma I've encountered that json-generator types references invalid internal namespace.

Issue can be fixed if type definition will be appended with next import at head of file:
```
import type * as Prisma from "./internal/prismaNamespace"
```
 
Image

P.S I'm sorry for not providing minimum reproducable repo.

### Steps to Reproduce

Install latest prisma, json-generator and check out at output dir file named `pjtg.ts`.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by x22dnk**
Fixes #516 

I tested it via running both normal for old and for a new client and import statement only appended for multifile client.

P.S I did not understand which tests you wanted me to add, as normal test for new client already exists.

### CODE REVIEW

File: assets/imports.d.ts
Comment (arthurfiorette) [inline assets/imports.d.ts:1]: What's the reason behind this empty file?

Comment (x22dnk) [reply assets/imports.d.ts:1]: Oh my bad, seems I somehow committed empty file.
Let me fix

File: src/util/declaration-writer.ts [hunk 1]
```diff
@@ -130,5 +130,14 @@ export async function getNamespacePrelude(namespace: string) {
   // Replaces the namespace with the provided namespace
   prelude = prelude.replace(/\$\$NAMESPACE\$\$/g, namespace);
 
+  if (isNewClient) {
+    const imports = await fs.readFile(IMPORTS_PATH, 'utf-8');
```
Comment (arthurfiorette) [inline src/util/declaration-writer.ts:134]: Instead of having to read a different file just for a single line import, please remove that file and simply use a literal string as I did in line 36.

**Review by arthurfiorette — CHANGES_REQUESTED** [review]
